export const sampleResponse = {  
  "request": {  
    "country": "uk",  
    "language": "en",  
    "location": "brighton",  
    "num_res": "20",  
    "offset": 0,  
    "output": "json_xs",  
    "page": 1,  
    "pretty": "1",  
    "product_type": "realestate",  
    "property_type": "property",  
    "size_type": "net",  
    "size_unit": "m2",  
    "sort": "nestoria_rank",  
    "listing_type": "buy"  
  },  
  "response": {  
    "application_response_code": "100",  
    "application_response_text": "listings returned for one unambiguous location",  
    "attribution": {  
      "img_height": 22,  
      "img_url": "https://resources.nestimg.com/nestoria/img/pbr_v1.png",  
      "img_width": 183,  
      "link_to_img": "http://www.nestoria.com"  
    },  
    "created_http": "Tue, 12 Nov 2019 15:01:33 GMT",  
    "created_unix": 1573570893,  
    "link_to_url": "https://www.nestoria.co.uk/brighton/property/buy",  
    "listings": [  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "NetHousePrices",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/3_bedroom_flat_112634085208873254.jpg",  
        "img_width": 400,  
        "keywords": "Needs Modernisation, No Chain, Kitchen, Basement, Gas Central Heating",  
        "latitude": 50.84949,  
        "lister_name": "King & Chasemore",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112634085208873254/title/5/1-1?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.1306921,  
        "price": 245000,  
        "price_currency": "£",  
        "price_formatted": "£245,000",  
        "price_high": 245000,  
        "price_low": 245000,  
        "price_type": "fixed",  
        "property_type": "flat",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Offered with no forward chain, this rarely available property is si...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_flat_112634085208873254.jpg",  
        "thumb_width": 80,  
        "title": "Burstead Close, Brighton, East Sussex, BN1",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "Home.co.uk",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/semi_detached_house_112503942656422528.jpg",  
        "img_width": 400,  
        "keywords": "Garden, Semi-Detached, En suite, Wood Floor, Double Bedroom, Kitchen, Parking, Patio, Cul-de-Sac",  
        "latitude": 50.86209,  
        "lister_name": "Spencer & Leigh",  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000112503942656422528/title/5/1-2?serpUid=&pt=1&ot=1&l=brighton&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 10,  
        "longitude": -0.125883,  
        "price": 375000,  
        "price_currency": "£",  
        "price_formatted": "£375,000",  
        "price_high": 375000,  
        "price_low": 375000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Guide price 375,000 400,000situated in a quiet cul-de-sac is this e...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/semi_detached_house_112503942656422528.jpg",  
        "thumb_width": 80,  
        "title": "Rotherfield Close, Hollingbury, Brighton",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      }    
    ],  
    "locations": [  
      {  
        "center_lat": 50.854603,  
        "center_long": -0.132899,  
        "long_title": "Brighton",  
        "place_name": "brighton",  
        "title": "Brighton"  
      }  
    ],  
    "page": 1,  
    "sort": "nestoria_rank",  
    "status_code": "200",  
    "status_text": "OK",  
    "thanks": "For using the Nestoria API.",  
    "total_pages": 150,  
    "total_results": 2992,  
    "_cu5t0mP434m_": "remove"  
  }  
}  