export const sampleResponse = {  
  "request": {  
    "country": "uk",  
    "language": "en",  
    "location": "brighton",  
    "num_res": "20",  
    "offset": 0,  
    "output": "json_xs",  
    "page": 1,  
    "pretty": "1",  
    "product_type": "realestate",  
    "property_type": "property",  
    "size_type": "net",  
    "size_unit": "m2",  
    "sort": "nestoria_rank",  
    "listing_type": "buy"  
  },  
  "response": {  
    "application_response_code": "100",  
    "application_response_text": "listings returned for one unambiguous location",  
    "attribution": {  
      "img_height": 22,  
      "img_url": "https://resources.nestimg.com/nestoria/img/pbr_v1.png",  
      "img_width": 183,  
      "link_to_img": "http://www.nestoria.com"  
    },  
    "created_http": "Tue, 12 Nov 2019 15:01:33 GMT",  
    "created_unix": 1573570893,  
    "link_to_url": "https://www.nestoria.co.uk/brighton/property/buy",  
    "listings": [  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "NetHousePrices",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/3_bedroom_flat_112634085208873254.jpg",  
        "img_width": 400,  
        "keywords": "Needs Modernisation, No Chain, Kitchen, Basement, Gas Central Heating",  
        "latitude": 50.84949,  
        "lister_name": "King & Chasemore",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112634085208873254/title/5/1-1?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.1306921,  
        "price": 245000,  
        "price_currency": "£",  
        "price_formatted": "£245,000",  
        "price_high": 245000,  
        "price_low": 245000,  
        "price_type": "fixed",  
        "property_type": "flat",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Offered with no forward chain, this rarely available property is si...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_flat_112634085208873254.jpg",  
        "thumb_width": 80,  
        "title": "Burstead Close, Brighton, East Sussex, BN1",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "Home.co.uk",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/semi_detached_house_112503942656422528.jpg",  
        "img_width": 400,  
        "keywords": "Garden, Semi-Detached, En suite, Wood Floor, Double Bedroom, Kitchen, Parking, Patio, Cul-de-Sac",  
        "latitude": 50.86209,  
        "lister_name": "Spencer & Leigh",  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000112503942656422528/title/5/1-2?serpUid=&pt=1&ot=1&l=brighton&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 10,  
        "longitude": -0.125883,  
        "price": 375000,  
        "price_currency": "£",  
        "price_formatted": "£375,000",  
        "price_high": 375000,  
        "price_low": 375000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Guide price 375,000 400,000situated in a quiet cul-de-sac is this e...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/semi_detached_house_112503942656422528.jpg",  
        "thumb_width": 80,  
        "title": "Rotherfield Close, Hollingbury, Brighton",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 4,  
        "car_spaces": 0,  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OnTheMarket.com",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/4_bedroom_detached_house_for_sale_112076603853277641.jpg",  
        "img_width": 400,  
        "keywords": "Detached, Garden, Garage",  
        "latitude": 50.866856,  
        "lister_name": "Brand Vaughan",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112076603853277641/title/5/1-3?serpUid=&pt=1&ot=1&l=brighton&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.153006,  
        "price": 895000,  
        "price_currency": "£",  
        "price_formatted": "£895,000",  
        "price_high": 895000,  
        "price_low": 895000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "You would be forgiven for not knowing this peaceful close in patcha...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/4_bedroom_detached_house_for_sale_112076603853277641.jpg",  
        "thumb_width": 80,  
        "title": "Court Close, Brighton, East Sussex, BN1",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 1,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OneDome",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/1_bedroom_flat_for_sale_112634159870430221.jpg",  
        "img_width": 400,  
        "keywords": "Needs Modernisation, High Ceilings, Double Bedroom, Kitchen, Reception",  
        "latitude": 50.833256,  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000112634159870430221/title/5/1-4?serpUid=&pt=1&ot=1&l=brighton&did=370851_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.132235,  
        "price": 169950,  
        "price_currency": "£",  
        "price_formatted": "£169,950",  
        "price_high": 169950,  
        "price_low": 169950,  
        "price_type": "fixed",  
        "property_type": "flat",  
        "room_number": 1,  
        "size": 0,  
        "size_type": "net",  
        "summary": "General description this well presented ground floor flat is entere...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_flat_for_sale_112634159870430221.jpg",  
        "thumb_width": 80,  
        "title": "GFF Upper Lewes Road Brighton BN2",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": 1,  
        "bedroom_number": 3,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "Moving Soon",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/shared_ownership_in_brighton_brighton_and_hove_3_bedroom_terraced_house_112379549379651234.jpg",  
        "img_width": 400,  
        "keywords": "Garden, En suite, Terraced, Victorian, Kitchen, Parking, Shared Ownership",  
        "latitude": 50.84537,  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000112379549379651234/title/5/1-5?serpUid=&pt=1&ot=1&l=brighton&did=111_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.1521731,  
        "price": 585000,  
        "price_currency": "£",  
        "price_formatted": "£585,000",  
        "price_high": 585000,  
        "price_low": 585000,  
        "price_type": "585000",  
        "property_type": "house",  
        "room_number": 3,  
        "size": 0,  
        "size_type": "net",  
        "summary": "3 bed houses available in brighton £204,750 for 35% share key featu...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/shared_ownership_in_brighton_brighton_and_hove_3_bedroom_terraced_house_112379549379651234.jpg",  
        "thumb_width": 80,  
        "title": "Preston Road, Brighton BN1, UK",  
        "updated_in_days": 42,  
        "updated_in_days_formatted": "first seen over a month ago"  
      },  
      {  
        "bathroom_number": 2,  
        "bedroom_number": 2,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "NetHousePrices",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/2_bedroom_maisonette_flat_112634088706470256.jpg",  
        "img_width": 400,  
        "keywords": "Share of Freehold, Garden, Victorian, Double Bedroom, Kitchen",  
        "latitude": 50.840942,  
        "lister_name": "Avard",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112634088706470256/title/5/1-6?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.1349114,  
        "price": 350000,  
        "price_currency": "£",  
        "price_formatted": "£350,000",  
        "price_high": 350000,  
        "price_low": 350000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Opportunity to purchase this large 2 double bedroom maisonette with...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_maisonette_flat_112634088706470256.jpg",  
        "thumb_width": 80,  
        "title": "St Andrews Road, Brighton, East Sussex, BN1",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 5,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "Home.co.uk",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/detached_house_112634180250306614.jpg",  
        "img_width": 400,  
        "keywords": "Detached",  
        "latitude": 50.846604,  
        "lister_name": "John Hilton",  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000112634180250306614/title/5/1-7?serpUid=&pt=1&ot=1&l=brighton&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 10,  
        "longitude": -0.109784,  
        "price": 440000,  
        "price_currency": "£",  
        "price_formatted": "£440,000",  
        "price_high": 440000,  
        "price_low": 440000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Attention investors a 5 bedroom licensed hmo property in a great lo...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/detached_house_112634180250306614.jpg",  
        "thumb_width": 80,  
        "title": "Widdicombe Way, Brighton - Detached",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 6,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "Home.co.uk",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/detached_house_112634178211792943.jpg",  
        "img_width": 400,  
        "keywords": "Detached, Double Bedroom, Kitchen",  
        "latitude": 50.832828,  
        "lister_name": "John Hilton",  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000112634178211792943/title/5/1-8?serpUid=&pt=1&ot=1&l=brighton&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 10,  
        "longitude": -0.12102,  
        "price": 620000,  
        "price_currency": "£",  
        "price_formatted": "£620,000",  
        "price_high": 620000,  
        "price_low": 620000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "A 6 double bedroom hmo property in a great location for student let...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/detached_house_112634178211792943.jpg",  
        "thumb_width": 80,  
        "title": "Brading Road, Brighton - Detached",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": 1,  
        "bedroom_number": 3,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "Moving Soon",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/shared_ownership_in_brighton_brighton_and_hove_3_bedroom_terraced_house_112379550103030796.jpg",  
        "img_width": 400,  
        "keywords": "Garden, En suite, Terraced, Victorian, Kitchen, Parking, Shared Ownership",  
        "latitude": 50.83849,  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000112379550103030796/title/5/1-9?serpUid=&pt=1&ot=1&l=brighton&did=111_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.1472018,  
        "price": 575000,  
        "price_currency": "£",  
        "price_formatted": "£575,000",  
        "price_high": 575000,  
        "price_low": 575000,  
        "price_type": "575000",  
        "property_type": "house",  
        "room_number": 3,  
        "size": 0,  
        "size_type": "net",  
        "summary": "3 bed houses available in brighton £201,250 for 35% share key featu...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/shared_ownership_in_brighton_brighton_and_hove_3_bedroom_terraced_house_112379550103030796.jpg",  
        "thumb_width": 80,  
        "title": "Preston Road, Brighton BN1, UK",  
        "updated_in_days": 42,  
        "updated_in_days_formatted": "first seen over a month ago"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 2,  
        "car_spaces": 0,  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OnTheMarket.com",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/2_bedroom_apartment_for_sale_112076607757878294.jpg",  
        "img_width": 400,  
        "keywords": "Balcony, Parking",  
        "latitude": 50.8198,  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112076607757878294/title/5/1-10?serpUid=&pt=1&ot=1&l=brighton&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.133369,  
        "price": 750000,  
        "price_currency": "£",  
        "price_formatted": "£750,000",  
        "price_high": 750000,  
        "price_low": 750000,  
        "price_type": "fixed",  
        "property_type": "flat",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Opposite the beach with a south facing balcony and secure parking, ...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_apartment_for_sale_112076607757878294.jpg",  
        "thumb_width": 80,  
        "title": "Marine Parade, Brighton, BN2",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": 0,  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OnTheMarket.com",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/3_bedroom_terraced_house_for_sale_112076618988103748.jpg",  
        "img_width": 400,  
        "keywords": "Terraced, Victorian, Patio",  
        "latitude": 50.81936,  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112076618988103748/title/5/1-11?serpUid=&pt=1&ot=1&l=brighton&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.120765,  
        "price": 500000,  
        "price_currency": "£",  
        "price_formatted": "£500,000",  
        "price_high": 500000,  
        "price_low": 500000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Quiet and comfortable this victorian three bedroom home with a rare...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_terraced_house_for_sale_112076618988103748.jpg",  
        "thumb_width": 80,  
        "title": "Great College Street, Brighton, East Sussex, BN2",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "Home.co.uk",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/semi_detached_house_112626994118743775.jpg",  
        "img_width": 400,  
        "keywords": "Garden, Semi-Detached, Double Bedroom, Garage, Kitchen",  
        "latitude": 50.859941,  
        "lister_name": "Spencer & Leigh",  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000112626994118743775/title/5/1-12?serpUid=&pt=1&ot=1&l=brighton&did=85_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 10,  
        "longitude": -0.137166,  
        "price": 400000,  
        "price_currency": "£",  
        "price_formatted": "£400,000",  
        "price_high": 400000,  
        "price_low": 400000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Guide price 400,000 425,000set back from the road with a lawn front...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/semi_detached_house_112626994118743775.jpg",  
        "thumb_width": 80,  
        "title": "Wilmington Way, Patcham, Brighton",  
        "updated_in_days": 2,  
        "updated_in_days_formatted": "first seen 2 days ago"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 4,  
        "car_spaces": 0,  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OnTheMarket.com",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/4_bedroom_detached_house_for_sale_112144285235805066.jpg",  
        "img_width": 400,  
        "keywords": "Detached, Garden, Garage",  
        "latitude": 50.816387,  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112144285235805066/title/5/1-13?serpUid=&pt=1&ot=1&l=brighton&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.102401,  
        "price": 1500000,  
        "price_currency": "£",  
        "price_formatted": "£1,500,000",  
        "price_high": 1500000,  
        "price_low": 1500000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Offers received with best & final dates to be confirmed. Developmen...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/4_bedroom_detached_house_for_sale_112144285235805066.jpg",  
        "thumb_width": 80,  
        "title": "Roedean Road, Brighton, BN2 - Garden",  
        "updated_in_days": 1,  
        "updated_in_days_formatted": "New"  
      },  
      {  
        "bathroom_number": 1,  
        "bedroom_number": 2,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "Moving Soon",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/2_bed_shared_ownership_apartment_in_brighton_montpelier_pl_111575769735158451.jpg",  
        "img_width": 400,  
        "keywords": "Furnished, Double Bedroom, Kitchen, Dishwasher, Shared Ownership",  
        "latitude": 50.826515,  
        "lister_url": "https://www.nestoria.co.uk/detail/0000000111575769735158451/title/5/1-14?serpUid=&pt=1&ot=1&l=brighton&did=111_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.1531474,  
        "price": 495000,  
        "price_currency": "£",  
        "price_formatted": "£495,000",  
        "price_high": 495000,  
        "price_low": 495000,  
        "price_type": "495000",  
        "property_type": "flat",  
        "room_number": 2,  
        "size": 0,  
        "size_type": "net",  
        "summary": "2 bedroom apartment available for shared ownership in brighton. Off...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/2_bed_shared_ownership_apartment_in_brighton_montpelier_pl_111575769735158451.jpg",  
        "thumb_width": 80,  
        "title": "Montpelier Place, Brighton BN1, UK",  
        "updated_in_days": 172,  
        "updated_in_days_formatted": "first seen over a month ago"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": 0,  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OnTheMarket.com",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/3_bedroom_semi_detached_house_for_sale_112527748504280411.jpg",  
        "img_width": 400,  
        "keywords": "Garden, Semi-Detached, Fireplace, Kitchen, Patio, Gas Central Heating",  
        "latitude": 50.86736,  
        "lister_name": "Spencer & Leigh",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112527748504280411/title/5/1-15?serpUid=&pt=1&ot=1&l=brighton&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.133872,  
        "price": 400000,  
        "price_currency": "£",  
        "price_formatted": "£400,000",  
        "price_high": 400000,  
        "price_low": 400000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Guide price £400,000 £425,000if you are a family that likes to ente...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_semi_detached_house_for_sale_112527748504280411.jpg",  
        "thumb_width": 80,  
        "title": "Mackie Avenue, Patcham, Brighton",  
        "updated_in_days": 2,  
        "updated_in_days_formatted": "first seen 2 days ago"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 2,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "NetHousePrices",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/2_bedroom_flat_112627027992077894.jpg",  
        "img_width": 400,  
        "keywords": "Shared Garden, Purpose Built, Double Bedroom, Kitchen, Lift, Parking",  
        "latitude": 50.847282,  
        "lister_name": "King & Chasemore",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112627027992077894/title/5/1-16?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.1506258,  
        "price": 300000,  
        "price_currency": "£",  
        "price_formatted": "£300,000",  
        "price_high": 300000,  
        "price_low": 300000,  
        "price_type": "fixed",  
        "property_type": "flat",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Two bedroom apartment ideal first time buy off road parking communa...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/2_bedroom_flat_112627027992077894.jpg",  
        "thumb_width": 80,  
        "title": "London Road, Brighton, East Sussex, BN1",  
        "updated_in_days": 2,  
        "updated_in_days_formatted": "first seen 2 days ago"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 1,  
        "car_spaces": "",  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "NetHousePrices",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/1_bedroom_ground_flat_112627024890187274.jpg",  
        "img_width": 400,  
        "keywords": "Garden, Conversion, Victorian, Kitchen",  
        "latitude": 50.841057,  
        "lister_name": "Cubit & West",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112627024890187274/title/5/1-17?serpUid=&pt=1&ot=1&l=brighton&did=90_high1&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.139722,  
        "price": 315000,  
        "price_currency": "£",  
        "price_formatted": "£315,000",  
        "price_high": 315000,  
        "price_low": 315000,  
        "price_type": "fixed",  
        "property_type": "flat",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Pretty victorian converted flat in the sought after 'golden triangl...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/1_bedroom_ground_flat_112627024890187274.jpg",  
        "thumb_width": 80,  
        "title": "Waldegrave Road, Brighton, East Sussex, BN1",  
        "updated_in_days": 2,  
        "updated_in_days_formatted": "first seen 2 days ago"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": 0,  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OnTheMarket.com",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/3_bedroom_end_of_terrace_house_for_sale_112076573352857879.jpg",  
        "img_width": 400,  
        "keywords": "Garden, Terraced, Georgian",  
        "latitude": 50.852234,  
        "lister_name": "Goldin Lemcke",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112076573352857879/title/5/1-18?serpUid=&pt=1&ot=1&l=brighton&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.137402,  
        "price": 549995,  
        "price_currency": "£",  
        "price_formatted": "£549,995",  
        "price_high": 549995,  
        "price_low": 549995,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "A most three bedroom georgian style end of terrace house, standing ...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_end_of_terrace_house_for_sale_112076573352857879.jpg",  
        "thumb_width": 80,  
        "title": "Surrenden Park, Brighton - Garden",  
        "updated_in_days": 3,  
        "updated_in_days_formatted": "first seen 3 days ago"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 5,  
        "car_spaces": 0,  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OnTheMarket.com",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/5_bedroom_house_for_sale_112280309810203627.jpg",  
        "img_width": 400,  
        "keywords": "Garden, No Chain, Conversion, Terraced, Modern",  
        "latitude": 50.8467,  
        "lister_name": "John Hilton",  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112280309810203627/title/5/1-19?serpUid=&pt=1&ot=1&l=brighton&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.108558,  
        "price": 365000,  
        "price_currency": "£",  
        "price_formatted": "£365,000",  
        "price_high": 365000,  
        "price_low": 365000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "An 1930's end of terrace residence with recent loft conversion prov...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/5_bedroom_house_for_sale_112280309810203627.jpg",  
        "thumb_width": 80,  
        "title": "Nyetimber Hill, Brighton - Garden",  
        "updated_in_days": 2,  
        "updated_in_days_formatted": "first seen 2 days ago"  
      },  
      {  
        "bathroom_number": "",  
        "bedroom_number": 3,  
        "car_spaces": 0,  
        "commission": 0,  
        "construction_year": 0,  
        "datasource_name": "OnTheMarket.com",  
        "img_height": 300,  
        "img_url": "https://imgs.nestimg.com/3_bedroom_house_for_sale_112076619348481083.jpg",  
        "img_width": 400,  
        "keywords": "Terraced, Kitchen",  
        "latitude": 50.8429,  
        "lister_url": "https://www.nestoria.co.uk/detail-int/0000000112076619348481083/title/5/1-20?serpUid=&pt=1&ot=1&l=brighton&did=105_default&t_sec=9&t_or=45&t_pvid=null&utm_source=api&utm_medium=external",  
        "listing_type": "buy",  
        "location_accuracy": 9,  
        "longitude": -0.155657,  
        "price": 535000,  
        "price_currency": "£",  
        "price_formatted": "£535,000",  
        "price_high": 535000,  
        "price_low": 535000,  
        "price_type": "fixed",  
        "property_type": "house",  
        "size": 0,  
        "size_type": "net",  
        "summary": "Asking price £535,000this property is located in one of brightons m...",  
        "thumb_height": 60,  
        "thumb_url": "https://imgs.nestimg.com/medium/3_bedroom_house_for_sale_112076619348481083.jpg",  
        "thumb_width": 80,  
        "title": "Scarborough Road, Brighton, BN1",  
        "updated_in_days": 2,  
        "updated_in_days_formatted": "first seen 2 days ago"  
      }  
    ],  
    "locations": [  
      {  
        "center_lat": 50.854603,  
        "center_long": -0.132899,  
        "long_title": "Brighton",  
        "place_name": "brighton",  
        "title": "Brighton"  
      }  
    ],  
    "page": 1,  
    "sort": "nestoria_rank",  
    "status_code": "200",  
    "status_text": "OK",  
    "thanks": "For using the Nestoria API.",  
    "total_pages": 150,  
    "total_results": 2992,  
    "_cu5t0mP434m_": "remove"  
  }  
}  